### ISSUE TITLE
Typo recv

### ISSUE THREAD

**Issue by kgv** [Trantect/win_driver_example#2]
[typo](https://github.com/Trantect/win_driver_example/blob/master/cargo.toml#L10):
~~recv~~ -> rev

And you can use `branch` or `rev`:

```shell
warning: dependency (winapi) specification is ambiguous. Only one of `branch`, `tag` or `rev` is allowed. This will be considered an error in future versions
```

**Comment by woodgear** [comment]
thanks for issue, it has been fixed.
